### ISSUE TITLE
States/City/Postal/Zip should be filtering based on what is fitlered already

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#142]
If Canada is selected, than only Canadian Provinces, Cities, and Postals should be shown.

If Canada and Ontario is selected, then only Cities and Postals in Ontario, Canada should be shown.

Etc.

**Comment by stephenmartin2951** [comment]
I can take a look at this

**Comment by stephenmartin2951** [comment]
@kellenwiltshire We want this to update once a state/country/etc is selected, right? Not wait for the Update Filter button to be pressed?

**Comment by kellenwiltshire** [comment]
Hmm this is a good thought... I guess we may want it to be more dhlynamic like that yeah.

**Comment by kellenwiltshire** [comment]
Not necessarily update the reviews themselves, but we can update the filters with refetching with UseSWR perhaps.

**Comment by stephenmartin2951** [comment]
Yeah I wasn't thinking the reviews themselves, but would be cool if the filter options refreshed dynamically like that. Thanks for the tip with UseSWR I've been trying to think of how I could do it.
