### ISSUE TITLE
Update Styling on Other Landlords Suggestions

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#148]
![image](https://github.com/RateTheLandlord/rtl-frontend/assets/31140634/533ac50a-ecaf-4741-b742-b6a9833438d4)

These should have similar rounding of corners are other UI elements. They should also be all the same size (smaller ones grow to match bigger ones.

**Comment by stephenmartin2951** [comment]
I'll take a look at this

**Comment by kellenwiltshire** [comment]
Do you think you'll have this done in the next couple days? Would be great to get it out with the next release. If not, no worries!

**Comment by stephenmartin2951** [comment]
I haven't had a chance to start working on it yet. I will start on it tonight and let you know how it's going.
