### ISSUE TITLE
Add Norway 🇳🇴 to the List of Selectable Countries for Reviews

### ISSUE THREAD

**Issue by DevDeb91** [RateTheLandlord/rtl-frontend#163]
### Description:

As discussed on Discord, I would like to request the addition of Norway 🇳🇴 to the list of selectable countries for reviewing landlords.

### Reason:

In Norway, landlords commonly contact previous landlords to ask for references about potential tenants. However, tenants do not have access to information about previous tenants and cannot obtain any references. Adding Norway to RateTheLandlord would help balance this discrepancy by allowing tenants to review and share information about landlords, thereby promoting transparency and fairness in the rental process.

### Additional Context:
Norway is divided into 15 administrative regions, called [counties](https://en.wikipedia.org/wiki/Counties_of_Norway).

**Comment by kellenwiltshire** [comment]
How's this coming along? No rush, just seeing if you need any help!

**Comment by DevDeb91** [comment]
Hi and thank you for your message!

I was able to configure something and add Norway to the local branch, but when I try to submit a review, I receive a 401 Unauthorized error. I can open a draft pull request after work if you want, or can I get some help with backend configurations? I'm not very experienced with backend.

**Comment by kellenwiltshire** [comment]
A draft PR is okay, I can take a look and see what the issues may be

**Comment by DevDeb91** [comment]
I tried pushing my branch to create a draft PR, but it seems I don't have the necessary permissions to do so, neither I can assign this issue to myself.  Is it possible to check this?

**Comment by kellenwiltshire** [comment]
Ah, you need to fork the repo rather than clone it. Then you should be able to make PRs
