### ISSUE TITLE
Map Improvement: Remove `-` from zip codes

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#171]
Some zip codes have a `-` in them, such as `12345-1234`. We will need to remove everything after the `-` in order to get the lat/lon for the zip code from the DB.

**Comment by stephenmartin2951** [comment]
Is this a change you are wanting made to the existing data?

**Comment by kellenwiltshire** [comment]
Just when it queries for the location info, just need to split on the -

**Comment by stephenmartin2951** [comment]
Understood. I'll take a look.
