### ISSUE TITLE
Add Sorting by Rating

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#3]
**Describe the solution you'd like**
Add Sorting by Rating (high to low, low to high)

**Comment by kellenwiltshire** [comment]
The API is ready for this. Just need to update the UI for sorting. Need to add `high` or `low` to the query params. `low` will return reviews lowest to highest. `high` will do the opposite.

ie - Added param would be `sort=low` or `sort=high`

**Comment by stephenmartin2951** [comment]
Does the backend need to be updated for this as well? For example, it looks like in review.controller that the @Query is set to accept 'az' | 'za' | 'new' | 'old' but not 'high' and 'low'

**Comment by kellenwiltshire** [comment]
Did you check the develop branch?

**Comment by stephenmartin2951** [comment]
Yeah I found what I needed when I synced my fork. But after syncing is when I ran into issues accessing the backend

**Comment by kellenwiltshire** [comment]
@stephenmartin2951 Are you still working on this?

**Comment by stephenmartin2951** [comment]
Yeah I know how to implement this but I'm still having issues getting the frontend to communicate with the backend since syncing my forks.
