### ISSUE TITLE
Add Ability to Select No State and Enter No City for Resource

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#46]
Need ability to not enter a state and city for a resource since there may be resources that are available anywhere in the country.

**Comment by stephenmartin2951** [comment]
I will take a look at this.

**Comment by kellenwiltshire** [comment]
Seems you can already not enter a city (though, the UI needs tweaking for showing data without a city). 

Just need an option for No State

**Comment by stephenmartin2951** [comment]
@kellenwiltshire I am still working on letting no state be selected. How do you want it to look? Keep the drop down with an included option for "No State"?
