### ISSUE TITLE
Sorting doesn't work with reaources

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#47]
Sorting doesn't work with resources.

Also, highest and lowest should be removed for resources page sorting.

**Comment by stephenmartin2951** [comment]
I can take a look at this. Is there a good way to populate some dummy resources?

**Comment by stephenmartin2951** [comment]
This will probably require some backend work? Probably need to make changes to tenant.resource.service.ts so it can handle sorting? Similar to row 12 in review.service.ts

**Comment by kellenwiltshire** [comment]
It may need backend work eventually. It shouldn't matter too much though since if we don't pass the query it won't use the query. 

And I will look into adding a new script for dummy resources similar to dummy reviews!
