### ISSUE TITLE
Landlord Page - Show Other Landlords

### ISSUE THREAD

**Issue by kellenwiltshire** [RateTheLandlord/rtl-frontend#97]
On the Landlord Pages, we should show other Landlords from the same area with their average rating so Tenants can see how the Landlords compare to each other.

Easiest solution would be to use the same city. If a Landlord has properties in more than 1 city, use the city they have the most in. If they don't have a clear winner for city, use the most recent review's city.

**Comment by stephenmartin2951** [comment]
So if a user searches a specific landlord we want other landlords in that area to appear?

**Comment by kellenwiltshire** [comment]
@stephenmartin2951 no, if they go to a landlords page (such as https://ratethelandlord.org/landlord/PETERBOROUGH%20ONTARIO%20HOUSING%20%20CO.) then it should show other landlords and their average rating at the bottom in simple cards. This way a user can see how that landlords compares to others from the same area.

**Comment by stephenmartin2951** [comment]
I see. I can work on this.

**Comment by kellenwiltshire** [comment]
@stephenmartin2951  How's this going?

**Comment by stephenmartin2951** [comment]
@kellenwiltshire I haven't had a chance to work on the issue specifically. I spent a few hours last weekend trying to get the new backend setup but wasn't having much luck and need to look at it some more.
